# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from python_protogen.products.understanding.ast import ast_service_pb2 as products_dot_understanding_dot_ast_dot_ast__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in products/understanding/ast/ast_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.stream_stream(
                '/data.speech.ast.ASTService/Translate',
                request_serializer=products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateRequest.SerializeToString,
                response_deserializer=products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateResponse.FromString,
                _registered_method=True)


class ASTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Translate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.stream_stream_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateRequest.FromString,
                    response_serializer=products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.speech.ast.ASTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data.speech.ast.ASTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Translate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/data.speech.ast.ASTService/Translate',
            products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateRequest.SerializeToString,
            products_dot_understanding_dot_ast_dot_ast__service__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
